service: growth-estimate-api

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: ap-southeast-2
  memorySize: 2000

plugins:
  - serverless-python-requirements
  - serverless-plugin-warmup

package:
  individually: false

custom:
  pythonRequirements:
    usePipenv: true
    dockerizePip: non-linux
    slim: true
    zip: true
    #    layer: true
  warmup:
    enabled: true
    events:
      - schedule: rate(5 minutes)


functions:
  calculate-estimate:
    handler: main.lambda_handler
    warmup: true
    #    layers:
    #      - arn:aws:lambda:ap-southeast-2:113088814899:layer:Klayers-python37-pandas:10
    #      - arn:aws:lambda:ap-southeast-2:113088814899:layer:Klayers-python37-requests:10
    events:
      - http:
          path: growth_estimate
          method: post
          cors: true
